---
- name: Installing and Launch Metricbeat
  hosts: webservers
  become: true
  tasks:

  - name: Download and install metricbeat
    apt:
     deb: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb

  - name: Drop in metricbeat-config.yml
    copy:
      src: /etc/ansible/files/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: Enable Docker metricbeat
    command: metricbeat modules enable docker

  - name: Setup metricbeat
    command: metricbeat setup

  - name: Start metricbeat
    command: systemctl start metricbeat

#  - name: Enable metricbeat
#    command: metricbeat -e

  - name: Enable service metricbeat on boot
    systemd:
      name: metricbeat
      enabled: yes